### ISSUE TITLE
The never ending loop problem

### ISSUE THREAD

**Issue by DavidParkin** [unusualpepe/mpv-multiloop#1]
An alternative might be to leave the 'l' key unbound and let the normal mpv operation continue.

A loop change can be determined by

> mp.observe_property("ab-loop-b", "string", on_abloop_change)

And then in on_abloop_change
>function on_abloop_change(name, value)
>> 		    start = mp.get_property('ab-loop-a')
>>		    finish = mp.get_property('ab-loop-b')

If the loop is being terminated value will be "no" or else you can save the values.
They can be restored with 
>mp.set_property('ab-loop-a')

Hope this helps.

**Comment by realblaag** [comment]
Thanks for opening the issue. I am quite busy lately, but I will look into it as soon as I have some free time.

**Comment by realblaag** [comment]
Initially I thought you meant that the transition in a loop from B to A could be observed with `mp.observe_property("ab-loop-b" ...)`, but now I see that's not the case. The event only gets fired when setting the property ab-loop-b, which I'd be doing on my own (so I don't see the need to observe it). Maybe I haven't understood you.

I tried to fix it by using recursive functions instead of the while statements, but it seems the keybindings still don't work while that is happening. I may do a final try observing 'time-pos' to see if that changes anything, and, sadly, leave it as is if I don't get satisfactory results.

**Comment by realblaag** [comment]
I was able to fix it by observing "time-pos". Thanks for your help, I didn't know about `mp.observe_property` and it was the key.
